# Generated by Django 5.1.7 on 2025-03-18 20:44

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('isbn', models.PositiveIntegerField(unique=True)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('education', 'Education'), ('entertainment', 'Entertainment'), ('comics', 'Comics'), ('biography', 'Biography'), ('history', 'History')], default='education', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('enrollment', models.CharField(max_length=40, unique=True)),
                ('branch', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='IssuedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuedate', models.DateField(auto_now=True)),
                ('expirydate', models.DateField(default=core.models.get_expiry)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_copies', to='core.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_books', to='core.student')),
            ],
        ),
    ]
